# Generated by Django 5.2.4 on 2025-12-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
