# Generated by Django 5.2.4 on 2025-12-04 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financerecord',
            name='order',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financerecord',
            name='payment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='orders.payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financerecord',
            name='user',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
