# Generated by Django 5.2.4 on 2025-12-27 09:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_enrollment_completion_date_enrollment_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('credits', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('semester', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester')], max_length=1)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='school.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='school.reportingsession')),
            ],
            options={
                'verbose_name': 'Course Unit',
                'verbose_name_plural': 'Course Units',
                'ordering': ['semester', 'title'],
                'unique_together': {('code', 'session', 'course')},
            },
        ),
    ]
