# Generated by Django 5.2.4 on 2025-10-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMIS', '0002_requirement_document_financialaccount_member_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
