# Generated by Django 5.2.4 on 2025-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMIS', '0003_alter_withdrawal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
