# Generated by Django 5.2.4 on 2025-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMIS', '0004_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
