# Generated by Django 5.2.4 on 2025-10-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMIS', '0004_withdrawal_account_number_withdrawal_bank_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('KCB', 'KCB Bank'), ('Equity', 'Equity Bank'), ('Cooperative', 'Cooperative Bank'), ('Absa', 'Absa Bank'), ('Stanbic', 'Stanbic Bank'), ('NCBA', 'NCBA Bank'), ('Family', 'Family Bank'), ('I&M', 'I&M Bank'), ('DTB', 'Diamond Trust Bank'), ('Standard Chartered', 'Standard Chartered Bank')], max_length=100, null=True),
        ),
    ]
