# Generated by Django 5.2.4 on 2025-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMIS', '0006_alter_member_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='disability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
