# Generated by Django 5.2.4 on 2025-10-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMIS', '0007_member_mobile_alter_member_disability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
