# Generated by Django 5.2.4 on 2025-10-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDMIS', '0008_alter_member_first_name_alter_member_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
