# Generated by Django 5.2.4 on 2025-09-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('finance', 'Finance'), ('normal', 'Normal User')], default='normal', help_text='User role. Default is Normal User.', max_length=20),
        ),
    ]
