# Generated by Django 5.2.4 on 2025-11-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='deriv_connected',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deriv_token',
        ),
    ]
