# Generated by Django 5.2.4 on 2025-11-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_role'),
        ('accounts', '0003_alter_account_is_active_alter_account_last_login'),
    ]

    operations = [
    ]
