# Generated by Django 5.2.4 on 2025-11-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20251123_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('finance', 'Finance'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
