# Generated by Django 5.2.4 on 2025-11-21 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_account_options_alter_category_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Log', 'verbose_name_plural': 'Admin Logs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='tradehistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trade History', 'verbose_name_plural': 'Trade Histories'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-added_at'], 'verbose_name': 'Wishlist Item', 'verbose_name_plural': 'Wishlist Items'},
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp'),
        ),
        migrations.AlterField(
            model_name='account',
            name='deriv_connected',
            field=models.BooleanField(default=False, help_text='Whether user has connected Deriv account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='deriv_token',
            field=models.CharField(blank=True, help_text='Deriv API token', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('finance', 'Finance'), ('user', 'User'), ('trader', 'Trader')], default='user', help_text='User role for system permissions', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last account update timestamp'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Log creation time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Category creation time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last category update time'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Message submission time'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When trade was closed', null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Trade creation time'),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='When trade was opened', null=True),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Transaction completion time', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Transaction creation time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Profile creation time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='losing_trades',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_amount_traded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_trades',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last profile update time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='winning_trades',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When item was added to wishlist'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_ac_email_b00920_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='accounts_ac_usernam_862e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['role'], name='accounts_ac_role_22b49e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['admin_user', 'created_at'], name='accounts_ad_admin_u_7d2943_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['action'], name='accounts_ad_action_fa9550_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='accounts_ca_slug_5ab157_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='accounts_ca_is_acti_da5efb_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email'], name='accounts_co_email_498f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read'], name='accounts_co_is_read_989691_idx'),
        ),
        migrations.AddIndex(
            model_name='tradehistory',
            index=models.Index(fields=['user', 'created_at'], name='accounts_tr_user_id_bbb149_idx'),
        ),
        migrations.AddIndex(
            model_name='tradehistory',
            index=models.Index(fields=['symbol'], name='accounts_tr_symbol_6b8266_idx'),
        ),
        migrations.AddIndex(
            model_name='tradehistory',
            index=models.Index(fields=['status'], name='accounts_tr_status_5566fc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='accounts_tr_user_id_b38c46_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='accounts_tr_transac_d339cb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='accounts_tr_status_9c451f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['account_level'], name='accounts_us_account_36c11a_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'product_id'], name='accounts_wi_user_id_7fb1f2_idx'),
        ),
    ]
